### ISSUE TITLE
met.no support

### ISSUE THREAD

**Issue by skelgaard** [decompil3d/lovelace-hourly-weather#113]
can you get this to work with met.no also ?

**Comment by decompil3d** [comment]
Does it not currently? Can you elaborate on what is broken?

**Comment by skelgaard** [comment]
![billede](https://user-images.githubusercontent.com/13235820/185701379-697855f9-2e34-4255-ad78-a6cf36b4f72d.png)

this is how mine look

**Comment by skelgaard** [comment]
ah seems i just need to read better the docs... got it working
