### ISSUE TITLE
Localization issue

### ISSUE THREAD

**Issue by valepe** [decompil3d/lovelace-hourly-weather#114]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
2022.8.6 (HA) - 4.2.4 (Hourly-Weather)

**Last working release (if known):**
not used before

**Browser and Operating System:**
Chrome on mac OS and android and Android companion application.

**Description of problem:**
Issue with the italian localization. The problem is that italian localization already exists but it isn't used in my system and english is used instead (I checked the language selection of my user). So the issue #70 isn't applicable.
Hour format and decimal point are correct.

**Javascript errors shown in the web inspector (if applicable):**
no errors in console panel

```

```

**Additional information:**
Home Assistant Core running in Docker

**Comment by decompil3d** [comment]
Can you please check the values of `window.localStorage.getItem('selectedlanguage')` and `window.localStorage.getItem('haServerLanguage')`? If you refresh your browser, does it fix the issue?

**Comment by valepe** [comment]
Both return null and refreshing (soft and hard) does nothing.

**Comment by valepe** [comment]
Forgot to add that this is a manual installation. No HACS

**Comment by decompil3d** [comment]
Hm -- HACS shouldn't have anything to do with it. Can you open your browser dev tools, select the `hourly-weather` element in the DOM explorer, then go to the console tab and run `$0.hass` and show me the output. I'm particularly interested in the `locale` key within. I'm wondering if your card is somehow not receiving proper config from HA.

**Comment by valepe** [comment]
Strange, I did it but `$0.hass` returns `undefined`

**Comment by decompil3d** [comment]
What about $0.tagName?

**Comment by valepe** [comment]
`BODY`

**Comment by decompil3d** [comment]
Ok, that means that you didn't select the right element in the elements tab. You'll want to use the element finder tool (usually in the top left of the dev tools pane) to select something in the hourly weather card, then scroll through the DOM explorer to find the `hourly-weather` tag and click it. Then run the `$0.hass` command in the console.

**Comment by valepe** [comment]
Ok, now I selected the right element. Thank you for your help.

This is the response from `$0.hass`:
```
...
    "panelUrl": "lovelace",
    "defaultPanel": "lovelace",
    "language": "it",
    "selectedLanguage": null,
    "locale": {
        "language": "it",
        "number_format": "language",
        "time_format": "language"
    },
...
```

**Comment by valepe** [comment]
No script errors and my HA istante isn't exposed to internet.

Suggestion: can you add a language option in the settings to override the system language?

**Comment by decompil3d** [comment]
@valepe Can you please try version 4.3.0-beta.0 to see if that helps? First, see if it just works due to the refactored logic around getting the HA server language. If not, then you can try setting the new `language` config option on the card to manually select your language.

**Comment by valepe** [comment]
Just tryed. The new detection method failed: language reverts to english.
But language option works fine.

Thanks

**Comment by decompil3d** [comment]
Ok, then I think we'll just move forward with this fix. Not sure why it isn't picking up things in your case otherwise -- will be hard to debug without a concrete repro case.
