### ISSUE TITLE
Wrong icons

### ISSUE THREAD

**Issue by valepe** [decompil3d/lovelace-hourly-weather#122]
**Checklist:**

- [ X] I updated to the latest version available
- [ X] I cleared the cache of my browser

**Release with the issue:**
Latest

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**
Openweathermap reports partly-cloudy during the night (see the pic after 03:00) but hourly-weather shows the day icon (with the sun). The sunrise is around 06:30 these days.
![IMG_20220824_182728](https://user-images.githubusercontent.com/47390680/186473019-b11b3b30-a7b0-4b2c-ae87-88c7eca4ab07.jpg)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by decompil3d** [comment]
This is by design. OpenWeatherMap reports the condition as partly-cloudy, which maps to that icon. The card does not track whether it is night or day, since the entity does not provide sunrise/sunset information.

**Comment by decompil3d** [comment]
Just to add some further thoughts here: while it's possible to get sunrise/sunset information for the _next_ such event from the `sun.sun` entity, it is not easy to get subsequent sunrise/sunset times from there. So, to be able to show night vs day icons here, we'd need to bundle some sort of library to determine sunrise/sunset times. This seems like overkill here, and as such it is not planned.
