### ISSUE TITLE
Allow templating for `name`

### ISSUE THREAD

**Issue by jeremysherriff** [decompil3d/lovelace-hourly-weather#143]
**Is your feature request related to a problem? Please describe.**
I would love to be able to dynamically change the header/label `name` attribute, so that I could make it say the current conditions.
Then I could make the header value say something like "Cloudy 15 °C", like this:
![image](https://user-images.githubusercontent.com/1082213/189508763-4a292115-35e5-4769-955a-c2d1f07d46bf.png)
This makes even more sense when using an `offset` value, as I am able to show the current state via the header and the future states in the bar.

**Describe the solution you'd like**
Allow the `name` value to be derived via a jinga2 template value.

**Describe alternatives you've considered**
Using a markdown card above the hourly weather card to show the current state, and aligning the cards closely together.  Setting `name` to a space character " " (if using the GUI editor, otherwise `name: null` via yaml as per documentation) allows the header line to disappear, so this is viable but then the styling is not consistent.

**Additional context**
Saw your card in a Reddit post today, nice work!

**Comment by decompil3d** [comment]
This can work -- just need to add name to the config values that we pass through the templating engine. Like your other request, I'll try to get to it when I can or someone else can contribute.
