### ISSUE TITLE
Card not visible on Fire (Fully Kiosk)

### ISSUE THREAD

**Issue by silversmarty** [decompil3d/lovelace-hourly-weather#144]
**Checklist:**

- [V ] I updated to the latest version available
- [ V] I cleared the cache of my browser

**Release with the issue:**
4.3.1

**Last working release (if known):**
unknown

**Browser and Operating System:**
Fully Kiosk on Amazon Fire

**Description of problem:**

The card is not visible on Fully Kiosk Browser

**Additional information:**

THe card is visible on my laptop without any problem

**Comment by decompil3d** [comment]
Interesting -- is there any way for you to see if there are any script errors in Fully Kiosk?

**Comment by silversmarty** [comment]
There should be an error instead of the card place (as if you make an error
in the hall, or if the entity is not available) but no. No error is
displayed :-(

I'm thinking about a CSS error, or something like this, but I'm not sure...

Le lun. 12 sept. 2022 à 03:19, Jonathan Keslin ***@***.***> a
écrit :

**Comment by decompil3d** [comment]
Can you try some of the ideas suggested in the second FAQ item here: https://www.fully-kiosk.com/en/#faqs

Does the card work on Chrome and/or the basic Android browser on the same device?

If it's just in Fully Kiosk, are you able to try the Chrome remote debugger to see if it is throwing some sort of error in the console?

**Comment by silversmarty** [comment]
No problem with Chrome on the same device.

I must admit I don't know how to debug Webview, it seems there is a line of code to be embedded in the app (FullyKiosk ?) itself.
From what I can see in the tablet "developpers settings", it's using Amazon System Webview (it's an Amazon Fire tablet).

Hope it helps

**Comment by decompil3d** [comment]
That's all helpful info. Can you try checking the Amazon Silk browser on that device too? Just trying to eliminate possibilities.

**Comment by silversmarty** [comment]
It's a Fire on which I've installed Android, so no Silk available (nor on the Play Store) :-(

**Comment by decompil3d** [comment]
Ah, so it's normal Android webview, not Amazon. Do you know what version of Android it is?

**Comment by silversmarty** [comment]
70.amazon-webview-v70-3538.3538110.137

**Comment by silversmarty** [comment]
Hello, any update on this bug ?
Thanks a lot !

**Comment by decompil3d** [comment]
Sorry -- I haven't had time to look into this more. I've been taking care of a new baby so my computer time is pretty limited right now. I'll likely have more time in October and November. Apologies for the delay.

**Comment by silversmarty** [comment]
Having 3 kids myself, I know what you're going through ;-) Take your time, and enjoy the moment!

**Comment by decompil3d** [comment]
Yup, this is number 3 for me as well. They definitely grow up fast. Thanks for your patience on this.

**Comment by rkoehler2017** [comment]
here are 3x Fire 7 Tablets with Fully Browser (for fire tablet) wich are working with this addon a 2 or three month
(only today the problem with a unknow Icon on Cloudy Snowy condition)

**Comment by decompil3d** [comment]
> (only today the problem with a unknow Icon on Cloudy Snowy condition)

Which weather integration are you using?

**Comment by decompil3d** [comment]
> type: custom:hourly-weather
> 
> today it is working, the state is cloudy, yesterday the state was  unknown or so, unfortunately no screenshot made
> 
> 

I mean the weather entity you're using. Which provider is it? I haven't seen cloudy-snowy before so wondering if I need to add support.

**Comment by rkoehler2017** [comment]
Deutscher Wetterdienst
and it was Cloudy Snowy outside, the state was unknown from hourly-weather integration
here 
![image](https://user-images.githubusercontent.com/31540737/206895694-60773765-a28d-4c4b-8e3b-f5a78456191b.png)

**Comment by decompil3d** [comment]
Gotcha -- sounds like the integration provided bad data. Thanks for the info.

Regarding the original issue reported in this ticket, it sounds like it may not repro for other users with similar setups. As such, I'm going to close this.
