### ISSUE TITLE
Wind bearing doesn't render for 359°

### ISSUE THREAD

**Issue by decompil3d** [decompil3d/lovelace-hourly-weather#196]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** 4.6.0

**Last working release (if known):** N/A

**Browser and Operating System:** iOS HA native app

**Description of problem:**
Wind direction doesn't show when bearing is 359 degrees. Likely math issue in bearing to direction logic.

![image](https://user-images.githubusercontent.com/21011599/197546469-694b7ed0-2f33-40a7-9d7f-e7449787224c.jpeg)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by decompil3d** [comment]
@pauln if you have a moment, mind taking a look? I can dig in next week if you don't get to it. Thanks!

**Comment by pauln** [comment]
@decompil3d Oops - I forgot to append an extra North to the directions array when implementing the localization support.  I've added 359° to the test data along with the fix in #202 to hopefully avoid any regressions.
