### ISSUE TITLE
Show wind barbs instead of text

### ISSUE THREAD

**Issue by spuljko** [decompil3d/lovelace-hourly-weather#213]
Wind information takes lots of space, especially on mobile devices. Instead of text it would be nice to have an option to display wind barbs.

**Comment by decompil3d** [comment]
Is this what you have in mind?

<img width="467" alt="image" src="https://user-images.githubusercontent.com/21011599/200079695-5dac1b38-98d4-4098-a7f4-58e44d294ff2.png">

**Comment by spuljko** [comment]
Yes.
