### ISSUE TITLE
Option to hide title

### ISSUE THREAD

**Issue by spuljko** [decompil3d/lovelace-hourly-weather#214]
Title display should be optional. For example, when displaying first 12h and 12-24h in vertical grid it doesn't look nice.

**Comment by decompil3d** [comment]
In the yaml, set `title: null`. That will hide the title.

**Comment by weedy171** [comment]
I love your card design. I like to drop the title as well. I tried the following yaml but still displays "Hourly Weather"

type: custom:hourly-weather
entity: weather.home_hourly
title: null
icons: true
show_wind: 'true'
show_precipitation_amounts: true
num_segments: '10'
show_precipitation_probability: true

**Comment by decompil3d** [comment]
> I love your card design. I like to drop the title as well. I tried the following yaml but still displays "Hourly Weather"
> 
> 
> 
> type: custom:hourly-weather
> 
> entity: weather.home_hourly
> 
> title: null
> 
> icons: true
> 
> show_wind: 'true'
> 
> show_precipitation_amounts: true
> 
> num_segments: '10'
> 
> show_precipitation_probability: true

Did you save and exit edit mode?

**Comment by weedy171** [comment]
Yes I did, thanks for the reply.

**Comment by weedy171** [comment]
it did not
![image](https://user-images.githubusercontent.com/10540855/217325819-479a45b0-10f2-4a1b-be0c-b430b1d20e8c.png)

**Comment by weedy171** [comment]
That works! thanks!
