### ISSUE TITLE
Darksky

### ISSUE THREAD

**Issue by Juggler00** [decompil3d/lovelace-hourly-weather#216]
I've just found your card and love the look of it. Currently, I'm using the DarkSky (https://www.home-assistant.io/integrations/darksky/) integration to gather my weather data. The problem is that it presents itself as a bunch of sensors, rather than a weather. entity.

Is there a way to pull the DarkSky sensor data into your card?

**Comment by decompil3d** [comment]
Glad you like the card 😄 

You could try creating a [template weather entity](https://www.home-assistant.io/integrations/weather.template/) based on the sensors and then using that for the card.

That said, isn't DarkSky shutting down their API in March? Maybe a good time to try a different weather provider 😉

**Comment by Juggler00** [comment]
Fair enough... thanks for all your work!!!

**Comment by Valdorama** [comment]
There are two Dark Sky integrations. This is the one you need to work with this card: https://www.home-assistant.io/integrations/weather.darksky/
