### ISSUE TITLE
Actions do not work

### ISSUE THREAD

**Issue by higbyk** [decompil3d/lovelace-hourly-weather#230]
**Is your feature request related to a problem? Please describe.**
I'd love to use this card on my homepage with a tap action that navigates to my weather page, but the card does not support tap actions.

**Describe the solution you'd like**
Add tap actions to the card, as well as hold and double-tap actions.

**Describe alternatives you've considered**
I'm not aware of a way around this.

**Additional context**
I love this card, but can't use where I'd like it most.

**Comment by decompil3d** [comment]
The card should already support these but it looks like they don't work. I'll have a look next week if I can.

**Comment by decompil3d** [comment]
Actually, I spoke too soon. Actions seem to work just fine. Have you tried configuring actions already? Tap, hold, and double-tap actions are all available and documented in the readme.
