### ISSUE TITLE
Wind barbs not showing properly

### ISSUE THREAD

**Issue by Motik68** [decompil3d/lovelace-hourly-weather#239]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** 4.9.0

**Last working release (if known):**

**Browser and Operating System:**
Opera, Chrome (Windows 10)
Home Assistant supervised on Debian

On another installation I have (in another home), using Home Assistant Operating System, barbs display correctly.

**Description of problem:**
The wind barbs do not display, showing instead dots at various positions:
![image](https://user-images.githubusercontent.com/22507182/204145249-a728ca28-6447-4788-9110-4b035bc39235.png)

Everything works fine when displaying wind speed and direction as text:
![image](https://user-images.githubusercontent.com/22507182/204145301-a5c0aee4-6106-4dd6-a0eb-7a606b47bff6.png)

Any idea?

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by decompil3d** [comment]
The dot means calm/light winds. It is in different positions because it's rotated for direction. The barb svgs are a little off center, but I didn't have time to dig in to improving them (they're from an open source library).

**Comment by Motik68** [comment]
@decompil3d Thank you for your quick answer.

I know that the dots mean calm winds, but the issue is that the card **always** displays them, regardless of the speed of the wind. If you look at the pictures I posted, the wind speeds range from 4 to 12 knots, and most of them should definitely be displayed as barbs.

Can you please have a look?

**Comment by decompil3d** [comment]
Oh interesting. Might be a bad conversion from knots. Can you please share the devtools state of the weather entity you're using? The full yaml including attributes.

**Comment by Motik68** [comment]
You are right, I checked my other HA installation, where wind barbs display correctly, and the speed unit is kph, no kn. So must definitely be something related with knots.

Here is the devtools state (I included only the first forecasts, as there are lots of them. Of course I will share the whole yaml if you need it):

`temperature: 11
temperature_unit: °C
humidity: 85
pressure: 1017.2
pressure_unit: hPa
wind_bearing: 155
wind_speed: 7.78
wind_speed_unit: kn
visibility_unit: km
precipitation_unit: mm
forecast:
  - datetime: '2022-11-27T19:00:00+00:00'
    condition: partlycloudy
    wind_bearing: 165
    temperature: 10.5
    wind_speed: 7.78
    precipitation: 0
  - datetime: '2022-11-27T20:00:00+00:00'
    condition: partlycloudy
    wind_bearing: 180
    temperature: 10
    wind_speed: 7.78
    precipitation: 0
  - datetime: '2022-11-27T21:00:00+00:00'
    condition: partlycloudy
    wind_bearing: 195
    temperature: 9.5
    wind_speed: 7.78
    precipitation: 0
  - datetime: '2022-11-27T22:00:00+00:00'
    condition: cloudy
    wind_bearing: 200
    temperature: 9.2
    wind_speed: 5.83
    precipitation: 0
  - datetime: '2022-11-27T23:00:00+00:00'
    condition: cloudy
    wind_bearing: 205
    temperature: 8.9
    wind_speed: 5.83
    precipitation: 0
  - datetime: '2022-11-28T00:00:00+00:00'
    condition: cloudy
    wind_bearing: 210
    temperature: 8.6
    wind_speed: 3.89
    precipitation: 0
`

**Comment by Motik68** [comment]
Backticks don't seem do work as I expected... Of course the bullet points are actually hyphens in the yaml.

**Comment by Motik68** [comment]
I confirm that 4.9.1 corrected the issue. Thanks!
