### ISSUE TITLE
Phone cant deep sleep. Partial wakelock MmapPlayback

### ISSUE THREAD

**Issue by nortuzar** [decompil3d/lovelace-hourly-weather#250]
Hi, i am troubleshooting a battery problem on my phone. It was consuming between 10-15% at night without usage. Using the app better battery stats I saw that the partial wakelock **MmapPlayback** from ha companion interrupts the deep sleep process.

I disable the BLE beacon thinking that was the problem, but nothing. This are the logs from the BBS
https://community-assets.home-assistant.io/optimized/4X/2/4/1/241d3376f535464cd2c675ad7fd580a95245e8fd_2_488x500.jpeg
https://community-assets.home-assistant.io/optimized/4X/3/3/6/336d592b0a183a08a64466385c7cf02ddbededa9_2_482x500.jpeg

I was using the lovelace hourly weather card on my main view, so I move to another view and now the partial wakelock **MmapPlayback** disappear, now the phone go to deep sleep

I´m really sorry if the problem is not the card but I´m pretty sure it is. 

Hope this can help!

**Comment by decompil3d** [comment]
Hi @nortuzar -- I haven't seen this myself, but perhaps we can try to narrow things down a bit.

Have you tried making a new dashboard with just the hourly weather card on it and seeing if that repros the battery drain?

**Comment by nortuzar** [comment]
Hi, I did a lot of troubleshooting and at the end was the generic camera integration feed the cause of the problem

I will close this, thanks for the quick reply
