### ISSUE TITLE
Cloudy icon not rendering

### ISSUE THREAD

**Issue by iprak** [decompil3d/lovelace-hourly-weather#297]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:** 2023.1.4

**Last working release (if known):**

**Browser and Operating System:** Win11/Chrome (109.0.5414.74)

**Description of problem:**

The cloudy icon does not seem to render.
![image](https://user-images.githubusercontent.com/6459774/212537299-2444cf87-c7e5-4260-aa63-f45f9783d85d.png)

Dev Tools indicated that weather-cloudy was applied
![image](https://user-images.githubusercontent.com/6459774/212537331-8237c8d6-db14-4100-ae01-6fb774de0fa5.png)

I would have expected the background color to be based on day/night time.

**Javascript errors shown in the web inspector (if applicable):**

None

**Additional information:**

**Comment by decompil3d** [comment]
This is by design. Icons do not render if there is not enough space available for them. These 1 segment wide spans are too narrow. Tooltips will still work on hover/touch though.
