### ISSUE TITLE
wind_bearing does not handle direction as string e.g. NNW

### ISSUE THREAD

**Issue by biffel** [decompil3d/lovelace-hourly-weather#303]
It appears that the current code expects the attribute wind_bearing in the forecast to be a numeric bearing in degrees.

The [Home Assistant documentation](https://developers.home-assistant.io/docs/core/entity/weather) offers two alternatives to weather forecast integrations - either numeric degrees or a string 1-3 chars representing direction (e.g. NNW).

|Name|Type|Description|
|---|---|---|
|wind_bearing|float or string|The current wind bearing in azimuth angle (degrees) or 1-3 letter cardinal direction.|

This second format does not appear to be supported. Can it be?

One example that outputs strings is the [Australian 'Bureau of Meteorology' custom integration](https://github.com/bremor/bureau_of_meteorology) available through HACS, which puts uppercase directions in wind_bearing (e.g. SSE, W, NE etc).

**Comment by decompil3d** [comment]
Excellent bug report! Thank you so much for these details. I'll look at this when I have time -- probably later this week. Contributions welcome if someone else gets to it first.

**Comment by biffel** [comment]
Thanks! Working for me. Shame the wind barb display option isn't available in this circumstance but great to have the directions displayed as text now.

**Comment by decompil3d** [comment]
Thanks for confirming that the fix works. Ya, the wind barb wouldn't be accurate anyway cause the cardinal directions are so imprecise. I figured it was better to block that combination rather than showing misleading info.
