### ISSUE TITLE
Add optional border for weather bar

### ISSUE THREAD

**Issue by crafty35a** [decompil3d/lovelace-hourly-weather#311]
**Is your feature request related to a problem? Please describe.**
When a weather type's background color matches the card background color, the weather bar looks a little odd:
![image](https://user-images.githubusercontent.com/1082003/214624351-8147599f-002e-4e5e-a136-6557a97aa20a.png)

**Describe the solution you'd like**
An option to add a simple 1 pixel border to the bar

Thanks for making this card, it works great!

**Comment by crafty35a** [comment]
Just in case anyone runs into this in the future, this is what I ended up doing for now, via card-mod:
```
    card_mod:
      style:
        weather-bar$: |
          .snowy {
            outline-style: solid;
            outline-width: 1px;
            outline-offset: -1px;
            outline-color: #E5E5E5;
          }
```
![image](https://user-images.githubusercontent.com/1082003/214638339-2b89a91c-4f56-49bf-bc28-85cb07e63490.png)

I opted to outline the Snowy sections, since snow is rather rare and this way I am not modifying the look of the bar when there is no snow in the forecast. If you wanted to outline the whole bar, something like this works:
```
    card_mod:
      style:
        weather-bar$: |
          .bar {
            outline-style: solid;
            outline-width: 1px;
            outline-color: #E5E5E5;
            border-radius: 10px;
          }
```

**Comment by decompil3d** [comment]
I appreciate the request. I'm concerned that changing this would open a can of worms for existing users, and would be quite complex when we account for custom colors and themes. Thus, I'm inclined to leave this as-is and, instead, suggest that folks use card-mod when they want this sort of customization. Thanks for posting the card-mod YAML that worked for you!
