### ISSUE TITLE
Add offset setting

### ISSUE THREAD

**Issue by decompil3d** [decompil3d/lovelace-hourly-weather#34]
Add support for starting the data a specified number of hours after the beginning of the data.

**Comment by jchhenderson** [comment]
this is great.

Would it be possible to have offset by the number of hours until midnight (i.e. show a "tomorrow" bar)?

**Comment by decompil3d** [comment]
> this is great.
> 
> 
> 
> Would it be possible to have offset by the number of hours until midnight (i.e. show a "tomorrow" bar or a "this afternoon" bar)?

Opened #62 to allow templates. That should allow what you're looking for and more.
