### ISSUE TITLE
Show day/date when spanning across days

### ISSUE THREAD

**Issue by theone11** [decompil3d/lovelace-hourly-weather#364]
**Is your feature request related to a problem? Please describe.**
I use OpenWeatherMap for the hourly weather and it gives data each 3 hours.
I have the card configured to show 36 segments that span multiple days but it is difficult to understand which day it is for each segment.

![image](https://user-images.githubusercontent.com/3348953/230740167-ffffd8bc-e9bd-4aca-bd0d-2eb6094521c0.png)

**Describe the solution you'd like**
It would be great if there was an option (1 or more) to enable showing day seperator and/or day and/or date

**Describe alternatives you've considered**
If not then maybe a color change of the text for each day (swap between 2 colors for each day change)

**Comment by decompil3d** [comment]
I like the idea, but not sure yet on the best way to do this in the UX. Let me think on it a bit. If folks have suggestions for me to consider (beyond your initial proposals above) please comment.

**Comment by decompil3d** [comment]
@theone11 Can you please give me your thoughts on some of these ideas?

- What if the "tick mark" for a segment was a different color at each day boundary? Like, in your screenshot, the mark between 9pm and 3am could be white instead of gray to indicate a day change.
- What if hovering on the time gave the time and date?

**Comment by theone11** [comment]
I like the optional option you suggested. My theme is indeed custom (AMOLED Blue)

**Comment by decompil3d** [comment]
Would you expect the date to show above the hour or below it? Here's what it looks like above, when using the mode that only shows dates on day boundaries:

<img width="455" alt="image" src="https://user-images.githubusercontent.com/21011599/234126856-bea3fe17-16cb-43e4-b24a-e288b464519a.png">

**Comment by theone11** [comment]
Above like in your picture. Looks excellent
