### ISSUE TITLE
request: option to set `label_spacing: 0`

### ISSUE THREAD

**Issue by RedNo7** [decompil3d/lovelace-hourly-weather#427]
**Is your feature request related to a problem? Please describe.**
This is associated only with weather from the UK Met Office which shows 3-hourly readings.
The card works, but there is very little info as you only get to see every 6 hours (label_spacing: 2).
If you check the card at 10am, you only see 2 labels; 13:00 and 19:00

**Describe the solution you'd like**
Ability to show every label (which is in reality every 3 hours).

**Describe alternatives you've considered**
1] not using the card (which would be a shame]
2] not seeing more than 4 labels for 24 hrs (4m, 10am, 4pm, 10pm) and 2-3 labels for a typical day (10am, 4pm, 10pm).

**Additional context**
screen shot of Met Office info at 10:09 BST.
![Screenshot 2023-06-22 at 10 09 18](https://github.com/decompil3d/lovelace-hourly-weather/assets/130979051/c1f9d3ac-ff8c-4088-8423-e9fef5ee3797)

**Comment by rhdny** [comment]
I have the same issue in NY.
