### ISSUE TITLE
request: ability to format date/time format

### ISSUE THREAD

**Issue by ge33ek** [decompil3d/lovelace-hourly-weather#435]
**Is your feature request related to a problem? Please describe.**
Not a problem, visual enhancement

**Describe the solution you'd like**
Simple provide the ability to enable 12hr/24hr/ AM / PM - fully descriptive version of the date etc. etc. 

**Describe alternatives you've considered**
I have checked all documentation on HACS and can't see any way to alter date and time formats.

**Additional context**
N/A

**Comment by decompil3d** [comment]
See #368

**Comment by ge33ek** [comment]
For context, and people that find this in future. 

Locale settings in the Profile page enable you to use HA’s pre-structured options, and, whilst it does work the list is limited.

equally, date filter options are also very limited and don’t offer full day name options, meaning you’d either have to manually modify this GIT js or wait for improved functionality here or in locale settings for the user.
