### ISSUE TITLE
Use decimal separator associated with selected number format

### ISSUE THREAD

**Issue by mathoudebine** [decompil3d/lovelace-hourly-weather#44]
**Is your feature request related to a problem? Please describe.**
The temperatures are always displayed using a period/dot for the decimal separator.
![temperatures_period](https://user-images.githubusercontent.com/38615348/176964538-0ea5a60a-a539-4fa7-8ee1-5e70a4d2dc66.png)

**Describe the solution you'd like**
The temperatures would be better displayed using the decimal separator associated with selected language (for example: can be a comma https://en.wikipedia.org/wiki/Decimal_separator#Usage_worldwide).
![temperatures_comma](https://user-images.githubusercontent.com/38615348/176964555-cfc48172-87dd-4caa-b8bf-bd3a94c8e3f7.png)

**Comment by decompil3d** [comment]
You're right -- I think it just needs a call to the number format utility in `custom-card-helpers`.

**Comment by mathoudebine** [comment]
Yes, I just found out that there is a "Number format" setting on the profile page:

![number_format](https://user-images.githubusercontent.com/38615348/176966275-4a4de6dd-e689-4a90-825e-4434691add27.png)

I think this setting should be used for number display

**Comment by decompil3d** [comment]
Can you try 2.3.3-beta.0 and let me know if it works for you?

**Comment by mathoudebine** [comment]
Unfortunately it does not work with 2.3.3-beta.0, temperatures are still displayed with period as a separator no matter which number format or language I chose :frowning_face:

**Comment by decompil3d** [comment]
Oops, I made the release wrong. Try 2.3.3-beta.1

**Comment by mathoudebine** [comment]
Works like a charm! Thanks for your work :rocket: 
![beta-version](https://user-images.githubusercontent.com/38615348/176979402-0d2dbda5-ce59-46ff-b934-bc5155a139a9.png)

**Comment by decompil3d** [comment]
Released in 2.3.3
