### ISSUE TITLE
hourly (offset vs num_segments)

### ISSUE THREAD

**Issue by LeiChat** [decompil3d/lovelace-hourly-weather#451]
Hi. At 08:00 the first segments shown is 13:00
I have tried varying the num_segments but cannot get it to show any earlier forecast data.

I'm using OpenWeatherMap hourly... but is that actually 3 hourly forecast data?

```
num_segments: '12'
label_spacing: '2'
```

![image](https://github.com/decompil3d/lovelace-hourly-weather/assets/23559551/034af574-bc66-4d78-af71-0bee88fba8c6)

When using the template example to show the rest of the day I'm not able to replicate the 'Next 12 Hours' example you have at the top of your repository documentation. It appears to be showing the next two days forecast.

```
num_segments: |
  {{ 24 - now().hour }}
label_spacing: |
  {% set segments = 24 - now().hour %}
  {{ 4 if segments > 12 else 2 }}
```

![image](https://github.com/decompil3d/lovelace-hourly-weather/assets/23559551/d08fc2ab-1223-48dc-9cbb-c2d8dd84dcb5)

How may I configure the card to display the times as per your screenshot, with AM/PM rather than 24 hour clock please?

**Comment by LeiChat** [comment]
It seems to have fixed itself... perhaps it was a glitch with OpenWeatherMap data.

Still keen to know if there's a way I may amend the 24 hour times to AM/PM please?

![image](https://github.com/decompil3d/lovelace-hourly-weather/assets/23559551/0a754661-8ffd-4394-b33f-e371944f7f67)

**Comment by decompil3d** [comment]
Glad it fixed itself. For the times, you can adjust your time format settings in your HA user settings. Click your user name in the HA sidebar and adjust the time format settings there.
