### ISSUE TITLE
Icon for Partly Cloudy missing

### ISSUE THREAD

**Issue by MickLesk** [decompil3d/lovelace-hourly-weather#475]
**Checklist:**

- [ x] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:** 4.13.0

**Last working release (if known):** ---

**Browser and Operating System:** Chrome / Firefox / Opera -- Windows 11 / Android 

**Description of problem:**
The Icon for "partly cloudy" missing. 

**Javascript errors shown in the web inspector (if applicable):** nope

```

```

**Additional information:**
![image](https://github.com/decompil3d/lovelace-hourly-weather/assets/47820557/25f0f6c1-08a3-40fe-aeda-de32da0b784b)

**Comment by decompil3d** [comment]
This is by design. If the icon wouldn't have enough space to fit, it won't render.
