### ISSUE TITLE
up the resolution

### ISSUE THREAD

**Issue by paqpaqpaq** [decompil3d/lovelace-hourly-weather#486]
I know it is the 'hourly' weather bar, but would it be possible to have like e.g. 5min increments instead of 60min?
That way the resolution, mainly of the x-axes time indicator will make any sense when e.g. there are only 4 segments. (It will just show 2 times)

**Comment by decompil3d** [comment]
Technically, the card shows segments of whatever size the weather entity provides. That's why the config setting is `num_segments` instead of `num_hours`. If you use a weather entity that offers finer grained weather forecasts then you'll get what you're looking for.
