### ISSUE TITLE
Not ready for new setup 2023.9

### ISSUE THREAD

**Issue by vingerha** [decompil3d/lovelace-hourly-weather#503]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Description of problem:**

With 2023.9 the whole concept of gathering forecasts changes. The card should indictae to get (subscribe) to the daily or hourly values. Certain integrations already adhere (met.no and meteaofrance) so no way to get them to provide hourly by itself (daily is default)

**Comment by decompil3d** [comment]
Thanks for letting me know. According to the [developer blog](https://developers.home-assistant.io/blog/2023/08/07/weather_entity_forecast_types/) on this, integrations should still offer the `forecast` attribute until 2024.3. So we should be OK for the time being. I'll investigate this more and see if I can make the card work with the new mechanism soon.

**Comment by vingerha** [comment]
Hi, I thought the same but meteo-france integration abandonded this one already now. They offered a hourly and a daily integration before...now just the single one. Met.no never offered hourly/daily but they can be queried now for both.
The ONLY card that works fafaik is the standard 'weather card' wiht both met.no and meteo-france.
So for me...I use the hourly card with meteo-france and it no longer works in 2023.9.x
You probably have also seen the increasing HA forum thread on this topic... lots of people arguing :)

**Comment by vingerha** [comment]
There is also a PR in the making to allow to create a sensor along ones own pref. Also that is subject of discussion :) 
So...maybe analyse what you may need to do but wait a while before acting?
