### ISSUE TITLE
Language problem

### ISSUE THREAD

**Issue by RobertoCravallo** [decompil3d/lovelace-hourly-weather#513]
**Checklist:**

- [ yes] I updated to the latest version available
- [ yes] I cleared the cache of my browser

**Release with the issue:**
  not sure

**Last working release (if known):**

**Browser and Operating System:**
  mac os all browsers, android all browsers and HAS App on android
 all browsers up to date (FF, CHROME, SAFARI, BRAVE)

**Description of problem:**
when turning icons: false, the shown text is not in German as set in my system. Setting Language: german does nothing. Clicking on the text, opens forecast etc, all in default language (german). So problem is with the text that replaces the icons.

This should be german.
![IdAW – Home Assistant 2023-09-12 17-43-54](https://github.com/decompil3d/lovelace-hourly-weather/assets/112649622/ad51c299-9a56-44dc-9de4-570873f374fe)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
Very strange: On an old Android tablet, running 9.1, the german text appears in the HAS-Android App. Not in the browsers. All logins with the same user and password.

**Comment by BlueSnake830** [comment]
![image](https://github.com/decompil3d/lovelace-hourly-weather/assets/75618694/d00f7558-fe83-43ce-ad9f-c2728c9cd417)

Good morning, I also configured for german language. The day is correct, but it states "rainy" instead of "regnerisch". Other weather cards show "Regnerisch".

**Comment by ikekreham** [comment]
Hello,
Same issue with French Language.  ;-)

**Comment by RkcCorian** [comment]
Same problem here, problem still exists

**Comment by nighto** [comment]
Apparently this has been fixed (at least for pt-BR), just tested and it shows with that language:
![image](https://github.com/user-attachments/assets/dfe37fa3-9e48-421b-9557-819cee40505b)

**Comment by nighto** [comment]
Added manually `language: de` and it seemed to work:
![image](https://github.com/user-attachments/assets/19c500b0-87e1-442a-95f7-8d45feb6eae2)
As well as `language: fr`:
![image](https://github.com/user-attachments/assets/dc1a9ee5-1168-4f4c-b76f-b20087eb9320)
I believe we can close this issue @decompil3d
