### ISSUE TITLE
Partly cloudy / clear night wrong icon name

### ISSUE THREAD

**Issue by ElHamster** [decompil3d/lovelace-hourly-weather#528]
**Release with the issue:**
I think all?

**Description of problem:**
Partly cloudy and clear night uses the wrong icon name.

In the code, the mappings between conditions and MDIs are held in the constant `ICONS`, most of which are without the `weather-` prefix, which is then added in `weather-bar.ts`.

The problem is that `partly-cloudy` and `clear-night` already have the `weather-` prefix in the `ICONS` constant, so the final string is currently `weather-weather-partly-cloudy` and `weather-weather-night`, which doesn't work.

So by removing the `weather-` from the `ICONS` constant, the icons should work.

**Additional information:**
Icon on pictogrammers.com: https://pictogrammers.com/library/mdi/icon/weather-partly-cloudy/

**Comment by decompil3d** [comment]
This is not a bug. If you look at the line immediately under the one that adds the `mdi:weather-` prefix, you'll see that it also handles the case where the condition name does not match the icon name and thus does not add the prefix:

https://github.com/decompil3d/lovelace-hourly-weather/blob/main/src/weather-bar.ts#L68-L70
