### ISSUE TITLE
Map US National Weather Service Condidtion to icon

### ISSUE THREAD

**Issue by mnewm4** [decompil3d/lovelace-hourly-weather#53]
Please map NWS "exceptional" to an icon.  Currently, it defaults to an alert icon.

- detailed_description: ''
  datetime: '2022-07-11T16:00:00-05:00'
  condition: exceptional
  precipitation_probability: 0
  wind_bearing: 90
  temperature: 101
  wind_speed: 10

**Comment by decompil3d** [comment]
Hi -- this is actually by design. Exceptional means unexpected weather, so I went with an alert icon. Do you have an alternative material design icon that you think makes more sense for this?

**Comment by mnewm4** [comment]
Hmm... I have it mapped to weather-sunny but I have only been using the NWS
integration for a few months and have only seen it used on clear, sunny
days so far.  The alert icon perhaps makes more sense though considering
(note the included example) that a condition of "exceptional"  and
temperatures >100 would be out of the ordinary vs the subjective
interpretation of it being a good thing (it's not).

**Comment by decompil3d** [comment]
Ya, I've been seeing it a lot lately here in the Seattle area because of wildfire smoke. And the default weather card uses an alert icon for it as well.
