### ISSUE TITLE
Scaling icons

### ISSUE THREAD

**Issue by noreithe** [decompil3d/lovelace-hourly-weather#547]
**Is your feature request related to a problem? Please describe.**
When there are a lot of changes in weather through day, icons are not visible on some of day parts.

**Describe the solution you'd like**
If it would be possible to scale down icons based on possible space?

**Describe alternatives you've considered**
Maybe possibility to hide weather graph and just show temperatures etc?

**Additional context**

Thanks a lot
![weather](https://github.com/decompil3d/lovelace-hourly-weather/assets/144952088/8884a8f5-85ac-4362-9402-42b782923366)

**Comment by decompil3d** [comment]
Hiding icons when they won't fit is by design. But if you want to hide the bar itself you can use the yaml setting `hide_bar: true`. Hope that helps.

**Comment by noreithe** [comment]
> Hiding icons when they won't fit is by design. But if you want to hide the bar itself you can use the yaml setting `hide_bar: true`. Hope that helps.

perfect, thanks a lot!
