### ISSUE TITLE
Repository decompil3d/lovelace-hourly-weather not found

### ISSUE THREAD

**Issue by amathews84** [decompil3d/lovelace-hourly-weather#558]
**Checklist:**

- [yes ] I updated to the latest version available
- [ yes] I cleared the cache of my browser

**Release with the issue:**
Latest version
**Last working release (if known):**
n/a
**Browser and Operating System:**
Chrome/Windows 11 and Android

Chrome 118.0.5993.118
Windows 11

**Description of problem:**
When I select the Easiest installation method (ie HACS) in the github page it directs me to the HACS page of the hourly weather card.  When I try to download it from the 3 dot menu it says "Repository decompil3d/lovelace-hourly-weather not found".  Not sure where to go from here to get the card up and running.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by decompil3d** [comment]
Sounds like your HACS installation may be broken. I cannot reproduce this issue. If you want, you can just download the files and manually place them as described in the README.
