### ISSUE TITLE
Use Hourly Weather Card as Android Widget

### ISSUE THREAD

**Issue by amathews84** [decompil3d/lovelace-hourly-weather#562]
**Is your feature request related to a problem? Please describe.**

I love this card as it looks like the Dark Sky Android widget that I miss.  However, I don't know how exactly I can make this card a widget on Android.  I have the home assistant companion app and the ability to add a HA template widget but not technically savvy enough to implement this idea.

**Describe the solution you'd like**

Looking for a clean way to display this card on my Android home screen exactly how I have it displayed on my Home Assistant dashboard

**Describe alternatives you've considered**

There is an app called Widgetify that can take a section of any webpage and display it as a widget.  However, I have run into bugs and was hoping for a cleaner, native solution.

**Additional context**

**Comment by decompil3d** [comment]
Sorry, but I don't own an Android device and have no idea what the widget story is there. I'm going to close this, but won't lock it, so if someone else has an idea they can reply.

**Comment by amathews84** [comment]
I was able to add this to my android home screen using an app called Widgetify:

![20240721_144907.jpg](https://github.com/user-attachments/assets/a03bb1b7-773f-4552-a55a-bedd07b32ff6)

**Comment by decompil3d** [comment]
> The only issue is that I need to have the weather updates based on my phone location and not my home assistant home location. Is there a weather API that would let me do this?

Most of the HA weather entities pull their location from your HA install. Some have you declare it as part of the integration config. To be honest, if it were me, I'd probably look at hosting the component from the card itself in a non-HA webpage and then integrate with some weather provider API and feed in the data. But that'll definitely require software development skills. If you're up for the challenge, you can look at how the card is loaded outside of HA within the tests - see `cypress/fixtures/harness.html`. It just mocks out the HA wrapper cards and data sources. Unfortunately, I won't have time to help with this endeavor. Hope this helps, though.
