### ISSUE TITLE
Height of the text area

### ISSUE THREAD

**Issue by howedeng123** [decompil3d/lovelace-hourly-weather#573]
<img width="456" alt="iShot_2023-11-12_20 42 07" src="https://github.com/decompil3d/lovelace-hourly-weather/assets/117459476/813b65d6-f128-4541-be00-e1cabad414b3">

Hello, I have adjusted the text size of the condition label using card-mod, but it seems that the top and bottom parts of the text have been cut off. How do I adjust the height of the text area?

Below is the code for the card

type: custom:hourly-weather
entity: weather.22_540892795637482_113_90683203935626
num_segments: '5'
offset: '0'
label_spacing: '1'
icons: false
show_wind: 'false'
show_date: 'false'
show_precipitation_amounts: false
show_precipitation_probability: false
hide_temperatures: ture
name: null
language: en
card_mod:
  style:
    .: |
      ha-card {
        border: none;
        background: none;
      }
    weather-bar$: |
      .hour {
        font-size: 1.5rem !important
      }
      .condition-label {
        font-size: 3rem !important
      }
      .bar, .bar > div {
        height: 80px !important;
      }

**Comment by decompil3d** [comment]
Add `overflow: visible !important;` to your `.condition-label` class.
