### ISSUE TITLE
Temporary error upon loading the card

### ISSUE THREAD

**Issue by afarago** [decompil3d/lovelace-hourly-weather#586]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
5.3.0

**Last working release (if known):**

**Browser and Operating System:**
Version 119.0.6045.160 (Official Build) (64-bit)
Windows 11

**Description of problem:**
Initial loading of the page shows an error, that disappears in <1 sec, still is quite disturbing.
![image](https://github.com/decompil3d/lovelace-hourly-weather/assets/4489389/41d71446-30a9-4811-ba93-f9a19e9bd444)

This comes upw even with the simplest layout of the card.

**Javascript errors shown in the web inspector (if applicable):**
none

**Additional information:**
example config tested:
```yaml
type: custom:hourly-weather
entity: weather.home
```

**Comment by decompil3d** [comment]
Interesting, I wonder if this is a result of the recent change to use a web service call to get forecasts from HA. Perhaps we can hold off on showing errors if the web service call hasn't completed yet. If someone has time to look at this I can look at a PR. Otherwise, I'll get to this when I can.

**Comment by evilmouse69** [comment]
I also got the same error come up on my little wall panel

![IMG_7597](https://github.com/decompil3d/lovelace-hourly-weather/assets/38438298/f9bc01dc-4b95-4d11-a629-5abd9672fb68)

**Comment by afarago** [comment]
So in the past days I was able to debug the problem, and get the root cause.

- (I have a quite big dashboard with multiple different cards, using Meteorologisk institutt (Met.no))
- initially we start the subscription with `subscribeToForecastEvents`
- upon loading card starts rendering `renderCore`
- this calls `const forecast = this.getForecast();`
- as there is no answer yet from the subscription ( `this.forecastEvent?.forecast` is equals null in `private getForecast()` that returns the default daily granularity from the `this.hass?.states[this.config.entity]?.attributes.forecast` (6 items with daily granularity))
- yields to error (`this._showError(this.localize('errors.too_many_segments_requested'))`)
- shortly HA kicks in for the subscription and `subscribeMessage` callback returns with the hourly distribution (24 entries in the array)
- card re-renders with correct content.

I have an initial suggestion, please feel to review the PR and comment/modify.
