### ISSUE TITLE
change "color-clear-night" and other divs bgcolor

### ISSUE THREAD

**Issue by djsomi** [decompil3d/lovelace-hourly-weather#607]
Hi All,

I would like to change --color-clear-night default color within the card style. I can't achieve this, can someone help how to do this?
I assuming this should work but not:

`
card_mod:
  style: |
    .clear-night {
      background-color: #f00 !important
      }
`

I can hardcore into in JS, but its not so elegant solution.

Many thanks,
Zoltan

**Comment by decompil3d** [comment]
Hi Zoltan, you should be able to use the `colors` option in yaml config to achieve this. See the docs here: https://github.com/decompil3d/lovelace-hourly-weather#color-options

**Comment by djsomi** [comment]
Thanks, sorry, I overthinked it!
