### ISSUE TITLE
Support night icons and colour when weather entity does not

### ISSUE THREAD

**Issue by alexeiw123** [decompil3d/lovelace-hourly-weather#619]
**Is your feature request related to a problem? Please describe.**
My weather entity does not provide night values in it's forecast, so there is no night formatting in the output.

See my screen grab compared to the one on this repository.
![image](https://github.com/decompil3d/lovelace-hourly-weather/assets/77809797/ab0120ef-0040-4efb-9c49-9b7ddbb76d98)
![image](https://github.com/decompil3d/lovelace-hourly-weather/assets/77809797/dad69cfb-e81a-4c5d-8768-399fac4b28ba)

**Describe the solution you'd like**
use the state of sun.sun to show forecasts as their night time equivalent

**Comment by decompil3d** [comment]
I wish it were that easy. But `sun.sun` doesn't provide forecast data. Just current value. And even with current day sunrise/set data, we can't determine sun state for subsequent days. HA would need to expose a service call to retrieve sunrise/set times for a given day.
