### ISSUE TITLE
Partly cloudy at night shows wrong icon

### ISSUE THREAD

**Issue by Dizzybacon** [decompil3d/lovelace-hourly-weather#624]
**Checklist:**

- [ ] I updated to the latest version available
- [ ] I cleared the cache of my browser

**Release with the issue:**
V5.3.0
**Last working release (if known):**

**Browser and Operating System:**
Chromium on Ubuntu

**Description of problem:**
When the forecast is partly cloudy during the night time the partly cloudy day time icon is shown 

**Javascript errors shown in the web inspector (if applicable):**

![screenshot](https://github.com/decompil3d/lovelace-hourly-weather/assets/53298818/2222f928-53e4-4b9c-aab9-9758c50b3b33)

**Additional information:**

**Comment by decompil3d** [comment]
See #122 and #519. This is a limitation of Home Assistant and weather integrations.
