### ISSUE TITLE
New night-partly-cloudy shown during day

### ISSUE THREAD

**Issue by variada** [decompil3d/lovelace-hourly-weather#692]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** 6.0.0

**Last working release (if known):** 5.4.0

**Browser and Operating System:** 

Brave. Windows 11

**Description of problem:**

the new partly cloudy at night icon shows up for the whole day. maybe because the condition started at night time? (can't see the beginning as I updated 9am) - see screenshot

**Additional information:**
![image](https://github.com/decompil3d/lovelace-hourly-weather/assets/83453466/88808522-0d96-4515-b5d9-4107c5ca1306)

**Comment by decompil3d** [comment]
Can you please share your latitude and longitude settings from your Home Assistant install? It's ok to drop the decimal or round a little for privacy. But the calculation for nighttime uses that info, so I'm curious if maybe yours is just set wrong.

**Comment by RK62** [comment]
Same problem here:
V5.4.0
![IMG_0251](https://github.com/decompil3d/lovelace-hourly-weather/assets/39200469/697a82a6-d6ad-4068-8560-bc6a67d8fdbc)

V6.0.0
![IMG_0250](https://github.com/decompil3d/lovelace-hourly-weather/assets/39200469/49b10d0d-f340-4b93-807e-9bd111bb9e6f)

**Comment by jane-t** [comment]
Same problem here.  
50.92957
-2.91327

SW England.

<img width="580" alt="image" src="https://github.com/decompil3d/lovelace-hourly-weather/assets/920792/09fe0976-191d-4b13-89cc-a83fc9379c26">

**Comment by decompil3d** [comment]
Thanks for the reports folks! I'll look at this more on Monday. Feel free to downgrade to v5 in the meantime.

Any further details on if you ever see the daytime partly cloudy condition, and what times that happens would be helpful. Also any detail on which weather integration you're using.

This works for me, so I'm gonna need to dig in more to understand why it doesn't work for y'all. There's clearly a bug somewhere.

**Comment by variada** [comment]
haven't seen the daytime cloudy condition since the update. using DWD (Deutscher Wetterdienst) weather integration (found at https://github.com/FL550/dwd_weather)

**Comment by jane-t** [comment]
I have it again today
<img width="575" alt="image" src="https://github.com/decompil3d/lovelace-hourly-weather/assets/920792/8728001e-3d87-458d-893b-6c958873b249">

<img width="555" alt="image" src="https://github.com/decompil3d/lovelace-hourly-weather/assets/920792/f29afad1-7106-44ce-a111-01e1ddaf46a0">
`
 - datetime: "2024-06-17T13:00:00+00:00"
    condition: partlycloudy
    temperature: 17.3
    pressure: 1011
    cloud_coverage: 48
    wind_speed: 5.58
    wind_bearing: 223
    uv_index: 6.01
    precipitation_probability: 0
    precipitation: 0
    apparent_temperature: 16.8
    dew_point: 11.1
    wind_gust_speed: 11.2
    humidity: 67
`

**Comment by 78andyp** [comment]
Same here:
![image](https://github.com/decompil3d/lovelace-hourly-weather/assets/99039295/93863374-32e1-48df-91d7-f7c798002c5e)
![image](https://github.com/decompil3d/lovelace-hourly-weather/assets/99039295/0d4517ac-52b2-4269-bc21-bed2af73e69d)
