### ISSUE TITLE
Resource not found on older browser.

### ISSUE THREAD

**Issue by formatBCE** [decompil3d/lovelace-hourly-weather#696]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
6.0.0

**Last working release (if known):**
5.4.0

**Browser and Operating System:**

Fully Kiosk Browser on Android 10.
It's Lenovo Clock 2, with old Android WebView version, no way to upgrade.

**Description of problem:**

After update to 6.0.0, browser cannot find card. It behaves as usually when there's no such card installed.
I tried to remove integration completely, install 6.0.0 from scratch, and upgrade from 5.4.0 to 6.0.0. between each operations I was rebootimg Home Assistant, clearing cache for Fully, and rebooting the clock itself.

Downgrade from 6.0 to 5.4 also doesn't work, only deleting and installing 5.4.0 clean works for me.

BTW, it's same device I have bug with time zone too...

From the obvious reason, I can't see console...

**Javascript errors shown in the web inspector (if applicable):**

```
N/A
```

**Additional information:**

**Comment by decompil3d** [comment]
Sorry to hear this. Unfortunately, without a console error to work off of, this is going to be hard to diagnose. It's most likely that some modern JS feature either in the card code or one of its dependencies is not compatible with your old webview version. You may need to just pin to the old card version.

I won't be able to keep the card working on very old browsers. I'm glad that at least a recent version works for you. I'm going to close this issue as Won't Fix. Sorry about that.
