### ISSUE TITLE
Language?

### ISSUE THREAD

**Issue by realjax** [decompil3d/lovelace-hourly-weather#70]
I use the openweathermap entity as you suggested which works fine.  I did however select the dutch language during setup of openweathermap, which is not reflected in the card that still uses the english language in the descriptions?

**Comment by realjax** [comment]
Cool. Will do!

**Comment by decompil3d** [comment]
@realjax I ended up handling this via machine translation in #77 to test out my new validation of new language PRs. Would you mind giving the new `src/localize/languages/nl.json` file a look to make sure that the machine translation is correct?

**Comment by valepe** [comment]
Same issue with the italian localization. The problem here is that italian localization already exists but it isn't used in my system (I checked the language selection of my user).
Hour format and decimal point are correct.
