### ISSUE TITLE
Forecast not avalaible since 2024.7.0 (and.1)

### ISSUE THREAD

**Issue by LioBoul** [decompil3d/lovelace-hourly-weather#709]
Since the 2 latests version of HA OS :

![IMG_9807](https://github.com/decompil3d/lovelace-hourly-weather/assets/162896032/e8a879c0-de0c-4ccc-88a2-f442c3c7d641)

Tested with 3 forecast: the same.

![IMG_9808](https://github.com/decompil3d/lovelace-hourly-weather/assets/162896032/f5961319-4c6b-41b2-beb9-9f02acb4ef9b)

Others weather integrations are OK with my forecast.

**Comment by LouPaloma** [comment]
:+1:

**Comment by cromelex** [comment]
Same issue here after upgrading to 2024.7

**Comment by andonevris** [comment]
> Same issue here after upgrading to 2024.7
> 
> Edit: actually, I just checked the latest release notes and this has supposedly been fixed. I was already on 6.0.2 but I redownloaded in HACS and this seems to have fixed the issue. Not sure if it was cache or what. So it is working at the moment.

Yes, can confirm.  Redownloading current version fixes it

**Comment by LioBoul** [comment]
Same for me! Thanks :-)

**Comment by stncttr908** [comment]
Confirmed here, thanks for the tip. I figured it was something to do with this? https://github.com/home-assistant/core/pull/118664

**Comment by decompil3d** [comment]
> Confirmed here, thanks for the tip. I figured it was something to do with this? https://github.com/home-assistant/core/pull/118664

Yup - indeed. And I fixed that in 6.0.2. Guess caching in HA frontend or HACS caused trouble. Glad it works. I'll close this issue for now.

**For anyone else who sees this:** if your card isn't working after 2024.7, just re-download the card at version 6.0.2 or later via HACS and it should work.

**Comment by Notrial** [comment]
I redownloaded through HACS and naturally it works in incognito Chrome and Safari, but can't get it to clear cache in Chrome for the life of me. I deleted site data and cleared data through dev console.
Anyone got any tips on how to thoroughly clear it?
