### ISSUE TITLE
What background color did you specify for this?

### ISSUE THREAD

**Issue by amathews84** [decompil3d/lovelace-hourly-weather#710]
https://raw.githubusercontent.com/decompil3d/lovelace-hourly-weather/main/hourly-weather.png

I'd like to add the same for mine.  Also, is there a list of similar colors that I can play around with?

**Comment by decompil3d** [comment]
It's this theme: https://github.com/basnijholt/lovelace-ios-dark-mode-theme

**Comment by amathews84** [comment]
Is there any way to theme just the card without theming the entire Lovelace UI?

**Comment by decompil3d** [comment]
You can apply a theme to a card, but I don't think you'd get the background unless the theme is built to apply to single cards. You should look into Home Assistant theming to learn more.
