### ISSUE TITLE
Not working with HA App

### ISSUE THREAD

**Issue by RkcCorian** [decompil3d/lovelace-hourly-weather#712]
**Checklist:**

- [DONE] I updated to the latest version available
- [DONE] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**
- PC: Win10 + Edge > Working fine
- Mobile: S23 Ultra + Edge > Working fine
- Mobile: S23 Ultra + HA App > Not working (Message: Forecast not available, Check the configured forecast entity)

**Description of problem:**

Mobile: S23 Ultra + HA App > Not working (Message: Forecast not available, Check the configured forecast entity)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
Pictures attached...

YAML
```
type: custom:hourly-weather
entity: weather.forecast_home
```
PC: Win10 + Edge
![PC + Edge](https://github.com/decompil3d/lovelace-hourly-weather/assets/79741077/7d5bac84-1f34-4a3a-9117-e1bccbeabff8)

Mobile: S23 Ultra + Edge
![Mobile S23 Ultra + Edge](https://github.com/decompil3d/lovelace-hourly-weather/assets/79741077/a1ba8aed-6bbf-489a-8671-514ab30cbd9b)

Mobile: S23 Ultra + HA App
![Mobile S23 Ultra + HA App](https://github.com/decompil3d/lovelace-hourly-weather/assets/79741077/cfc2f5e2-ce97-46ea-b5cd-f1e5c02e2caa)

**Comment by Turton** [comment]
Same issue:  "Forecast not available".  The issue seems to be limited to the mobile Android app.  Desktop Edge, mobile iOS work fine.

**Comment by decompil3d** [comment]
Have you re-downloaded the card in HACS? It seems like that's helped other folks with this issue.

**Comment by Turton** [comment]
Thanks @decompil3d, that worked.

**Comment by RkcCorian** [comment]
I can also confirm that it is working again after downloading fresh again. How to proceed here? Is an action needed to prevent this in future or will the ticket be simply closed? Greetings!

**Comment by decompil3d** [comment]
All good - I'll close the ticket. Glad it's working for you now.
