### ISSUE TITLE
Ability to set what day to show

### ISSUE THREAD

**Issue by rasmusson** [decompil3d/lovelace-hourly-weather#732]
**Is your feature request related to a problem? Please describe.**
I want to be able to use this card for tomorrows weather or the day after that. 

**Describe the solution you'd like**
A attribute setting number of days in the future you want the card to start displaying weather for

**Describe alternatives you've considered**
It could be possible to do using the offset but then, the offset need to be calculated based on the current time to get a offset that is equal to the start of the next day

**Comment by decompil3d** [comment]
Please see the Templating section of the Readme. It shows how to do exactly this.

https://github.com/decompil3d/lovelace-hourly-weather?tab=readme-ov-file#templating
