### ISSUE TITLE
Card always English, not German

### ISSUE THREAD

**Issue by LuckyTriple7** [decompil3d/lovelace-hourly-weather#80]
- [ X ] I updated to the latest version available
- [ X ] I cleared the cache of my browser

**Browser and Operating System:**
Windows 11, Chrome 103.0.5060.134

My HA language is German, but the map is always displayed in English. The map is also displayed in English in the companion app.

![image](https://user-images.githubusercontent.com/60685158/182328924-0333a438-6584-4ad9-858d-f68f94ee5552.png)

I can see a German translation in the sources, but it probably doesn't work.

**Comment by decompil3d** [comment]
Here is a workaround: If you go to your user menu and then choose a different language and then back to German, it should work. I'll play around with code structure to see if I can make it respect the base HA locale. Right now, it depends on the `selectedLanguage` key in browser local storage. The localization logic all came from the custom card template repo I started with, so I need to dig in more to see how I can change how that works. Will leave this issue open to track that.

**Comment by Breakingx** [comment]
still not working.
