### ISSUE TITLE
TypeError: undefined is not an object (evaluating 't.locale')

### ISSUE THREAD

**Issue by ItsEcholot** [decompil3d/lovelace-hourly-weather#86]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
v4.2.1
**Last working release (if known):**

**Browser and Operating System:**
Safari 15.5, MacOS 12.4

**Description of problem:**
Card doesn't show up, the following error is thrown in the console.

**Javascript errors shown in the web inspector (if applicable):**

```
[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 't.locale')
	performUpdate (hourly-weather.js:11:4941)
	(anonymous function) (hourly-weather.js:11:4454)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 't.locale')
	(anonymous function) (hourly-weather.js:11:4394)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
```

**Comment by databoy2k** [comment]
I can't tell if this is related or the same or just similar. I've got the same issue of the card not showing up. Console:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'locale')
    at co.shouldUpdate (hourly-weather.js?hacstag=499270202421:259:2419)
    at co.performUpdate (hourly-weather.js?hacstag=499270202421:11:4637)
    at co.scheduleUpdate (hourly-weather.js?hacstag=499270202421:11:4445)
    at co._$Ej (hourly-weather.js?hacstag=499270202421:11:4353)
```

**Comment by Fox350** [comment]
I do have the card programmed and it was working before 4.2.1.  Now, I see it in the editor but it do not show up anymore.  Strangely, when I change something in the HA frontend editor the card appear.  But not when normal browsing

**Comment by decompil3d** [comment]
Thank you for the report. I think it's a timing bug. I have a fix in #87 that I'll get merged and released shortly.

**Comment by decompil3d** [comment]
Fixed in 4.2.2. Thanks again for reporting the issue!

**Comment by decompil3d** [comment]
Actually, found one more error case. Fix incoming.

**Comment by Fox350** [comment]
Thanks to you and great work I find it really useful.  👍

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by decompil3d** [comment]
Ok, confirmed that 4.2.3 does indeed fix the issue. Thanks again folks!

**Comment by Fox350** [comment]
Yep 4.2.2 did not for me but 4.2.3 did the job.  I use French in HA.  Thanks again

**Comment by ItsEcholot** [comment]
Thanks for the quick fix, works as expected now 👍
