### ISSUE TITLE
Option to hide the card title

### ISSUE THREAD

**Issue by jane-t** [decompil3d/lovelace-hourly-weather#91]
**Is your feature request related to a problem? Please describe.**
I am using the Hourly weather card on a small 7" tablet as our in kitchen display.   So every pixel counts.  

**Describe the solution you'd like**
I would like a way to hide the title.  Currently if you do not enter a title it defaults to a value of "Hourly Weather".  Ideally I would like this to work like other cards which when you leave the title blank it is not displayed.

**Comment by decompil3d** [comment]
If you set the title to `null` in the yaml view, it should hide the title when you save the card. Give that a try and let me know how it goes.

**Comment by jane-t** [comment]
Thanks, that did it.
