### ISSUE TITLE
Template expression example don't work wih num_segments (works first time in preview)

### ISSUE THREAD

**Issue by flemmingss** [decompil3d/lovelace-hourly-weather#92]
**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue:** 4.2.3

**Last working release (if known):** Don' know

**Browser and Operating System:** Windows 10, Google Chrome

**Description of problem:**
The card is working, but If I insert the example code the card gets hidden/disrepair 
`um_segments: |
  {{ 24 - now().hour }}`
![image](https://user-images.githubusercontent.com/25674067/183396793-5cba5411-a23d-4e7b-9ec6-bd9c62e822c9.png)

**Javascript errors shown in the web inspector (if applicable):**

![image](https://user-images.githubusercontent.com/25674067/183397596-a421fdae-ec62-4859-8429-4dcac59f161d.png)

**Additional information:**
Don't know if the card or the template code is the issue

**Comment by Cpublaster** [comment]
Same here, thought the issue was related to my template code but the example code also does not work for me.
